### ISSUE TITLE
Listing projects suggestions works slow or times out on larger number of projects set for JIT access

### ISSUE THREAD

**Issue by kamil-mt** [GoogleCloudPlatform/jit-access#180]
On the first step of choosing project it takes a long time or times out when listing projects matching the pattern. 

We have RESOURCE_SCOPE set to point to our organization. We have 2 jit instances:
- on production one we have jit available for 14 projects out of 60 in total and it times out when listing projects. (When we had less projects available for jit on production it was working)
- on staging jit instance we have 6 projects set with jit out of all organization 60 and it works there (quite slow, but works). 

Maybe there is a way to speed it up or provide some env variable at least to increase timeout for listing projects suggestions. Other possible solution could be possibility to add custom list of project under RESOURCE_SCOPE variable so that there would be option to provide list of projects that are configured for jit access only.

**Comment by jpassing** [comment]
Yes, listing projects can be quite slow, especially in larger organizations. However, 60 projects is not a lot, so I'm a bit surprised you're running into timeouts with that number of projects already.

FWIW, the app saves your last-used project in browser storage, and you can always enter a project ID manually. That softens the impact a bit, but is obviously not a real solution.

Under the hood, JIT Access [calls the Asset Inventory API](https://github.com/GoogleCloudPlatform/jit-access/blob/c0792baf35861cc91e1c96aafd296db7d64a4bed/sources/src/main/java/com/google/solutions/jitaccess/core/adapters/AssetInventoryAdapter.java#L81) to determine the user's list of projects, and this call is what causes the slowness. Caching wouldn't help very much because the results are different for every user.

There are a few options, but none of them are great:
1. Increase the timeout or make it configurable as you suggested.
2. Use [`projects:search`](https://cloud.google.com/resource-manager/reference/rest/v3/projects/search) to determine the list of projects. That's much faster, but the results would be incomplete as `projects:search` doesn't consider projects to which the user has eligible access to only.
3. List all projects that the underlying service account has access to. That's fast too, but might disclose too much information (too many projects) to users.

**Comment by omarst2** [comment]
I'm also seeing the same timeout error and i have 50 projects under the folder i'm monitoring

**Comment by abdolence** [comment]
@jpassing this is hunting us for a while. Will you accept PR where we can optionally specify predefined list of projects making it is much faster and without using GCP API at all?

**Comment by snowytoxa** [comment]
we are facing the same issue

**Comment by jpassing** [comment]
How about we...

* Implement option 3 from the comment above 
  > List all projects that the underlying service account has access to. That's fast too, but might disclose too much information (too many projects) to users.

   and
* Add a configuration option that lets you toggle between the current (slow and strict) and this alternate (fast and lax) behavior.

@abdolence, I'd be open to a PR, but I figure this might be easier to maintain than a static project list in the config?

**Comment by abdolence** [comment]
Agree, option 3 probably is easier to maintain. I'll give a try soon.

**Comment by abdolence** [comment]
@jpassing 
I made some implementation here:
https://github.com/GoogleCloudPlatform/jit-access/pull/201

Let me know if this is something you consider to fix this issue?

**Comment by jpassing** [comment]
With [Release 1.5](https://github.com/GoogleCloudPlatform/jit-access/releases/tag/1.5.0), you can now configure a `AVAILABLE_PROJECTS_QUERY` and let JIT Access perform a (non-personalized) search instead of performing a Policy Analyzer query to populate the project-autocompleter. This approach does come with [some tradeoffs](https://github.com/GoogleCloudPlatform/jit-access/wiki/Configuration#:~:text=AVAILABLE_PROJECTS_QUERY), but it's much faster. So I guess we can close this issue now.

Thanks again @abdolence for contributing this feature in #201.

**Comment by jpassing** [comment]
> I think `search` method in Resource Manager uses the format `field:value`, not `field=value`. So, shouldn't it be defined as `state:ACTIVE`?

Thanks! I updated the documentation.
