### ISSUE TITLE
Group members don't have permission to activate roles

### ISSUE THREAD

**Issue by ottlngr** [GoogleCloudPlatform/jit-access#228]
I have gathered several user accounts in a Google Workspace group and want the members of the group to be able to activate roles from a given set using jit-access.

I followed the documentation to add the IAM binding for this group:

```
gcloud projects add-iam-policy-binding my-project --member group:jit-test@domain.de --role roles/compute.admin --condition "
title=JIT access,expression=has({}.jitAccessContraint)"
```
But when a member of the group selects "my-project" in jit-access, the following error pops up:

> The project doesn't exist, or you don't have permission to activate any roles in this project

jit-access is set up correctly in general, as activating roles works if the IAM binding is made for a single user. What am I missing? The docs clearly (?) note that that users as well as groups are supported. 

I'm using other GCP features like IAP with groups as well, and never had a problem with it. So why does it seem jit-access can't look up the members of the group?

**Comment by radwo** [comment]
Did you [grant access to allow the application to resolve group memberships](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#grant_access_to_allow_the_application_to_resolve_group_memberships)? I had the same issue when I missed this step.

**Comment by ottlngr** [comment]
Thanks for the hint, I indeed missed that step. The jitaccess service account does now have the Group Reader role in Google Workspace, but apparently still can not resolve the group memberships - jitaccess still shows the same error message as mentioned above...

**Comment by jpassing** [comment]
Does it work correctly if you grant the role to a user instead of a group? If that doesn't work either, then I suspect that the application's service account doesn't have sufficient access. The service account [must have Security Admin and  Cloud Asset Viewer access](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#grant-the-just-in-time-access-application-permission-to-manage-iam-bindings) to the organization, folder, or project referenced in `RESOURCE_SCOPE`, and it can only "see" role bindings within that part of the resource hierarchy.

**Comment by jpassing** [comment]
This all looks good.

Is it possible that you're using multiple  Cloud Identity/Workspace accounts? For group resolution to work correctly, ...

* the Cloud Identity/Workspace account associated with the Google Cloud organization that contains the JIT Access project,
* the Cloud Identity/Workspace account containing the group in question, and
* the Cloud Identity/Workspace account in which you grant the _Group Reader_ admin role

must all be the same. If they're not, then it would explain why JIT Access (or more precisely, the underlying Policy Analyzer API) ignores the group.

It might also be worth performing a Policy Analyzer query manually:

1. Go to IAM > Policy Analyzer > Custom query
2. Under _Configure your query_, set:

   * Scope: folder you configured as `RESOURCE_SCOPE`
   * Resource: `//cloudresourcemanager.googleapis.com/projects/PROJECT` where `PROJECT` is the project you're trying to let group members access

3. Under _Set advanced options_, set

   * List individual users inside groups: enabled

4. Click Analyze

Does the result list group members individually (indicating that group resolution worked) or is it also just showing the group?

**Comment by ottlngr** [comment]
Hi @jpassing ,

thanks for your detailed answer.

Using the query in Policy Analyzer shows, that the group resolutions works. I tested this using my GCP-Account + Workspace Group Reader Role. I also used gcloud SDK to run the same query using service account impersonation and group resolution also worked when impersonating my jitaccess service account. So it seems to be all fine on the IAM/policy side. 

I'm running jitaccess in Cloud Run - is there any possibility to extend jitaccess' logging? Currently the log only shows a request to /api/projects/.../roles, which is responded with HTTP 200, but an empty array of roles.

**Comment by jpassing** [comment]
> Using the query in Policy Analyzer shows, that the group resolutions works. I tested this using my GCP-Account + Workspace Group Reader Role. I also used gcloud SDK to run the same query using service account impersonation and group resolution also worked when impersonating my jitaccess service account. So it seems to be all fine on the IAM/policy side.

Thanks for testing this, and sorry for the late reply.

Is the project that contains the JIT Access deployment part of a VPC-SC perimeter? That's the only difference I could think of that might explain why the query works when you perform it manually, but doesn't return the expected results when performed by the application.

> I'm running jitaccess in Cloud Run - is there any possibility to extend jitaccess' logging? 

The issue here is that the API doesn't return the expected result, so there isn't much that the application could log. However, what you could do is [change your configuration so that JIT Access uses the `AssetInventory` catalog](https://googlecloudplatform.github.io/jit-access/configure-catalogs/#assetinventory-catalog). With that configuration, JIT Access performs the group resolution itself (as opposed to letting the PolicyAnalzyer API do the resolution) and it's possible that you'll get additional information in the logs.

**Comment by knormanDL** [comment]
Experiencing this same issue on a fresh deploy, utilizing the `AssetInventory` catalog method from the jump.

I did notice some interesting behavior for multi-party approval flows depending on how the role is associated to the user:

**If the requesting user is indirectly granted role via group:**
Requestor receives error:
  > The project doesn't exist, or you don't have permission to activate any roles in this project

**If the requesting user is directly granted role via user principal assignment:**
1. Requestor is able to see and select available roles and proceed to approver selection
2. **All** users, including users granted role indirectly via group, are visible in approver selection
3. Notifications can be sent to all approvers, direct and indirect:
    - Approvers granted role via user principal are able to approve, and role is enabled
    - Approvers granted role via membership in group principal receive the following error:
      - The user `$USER` is not allowed to activate `$ROLE` using MPA (HTTP 403: error)

**Comment by cwalshProlific** [comment]
identical issue to @knormanDL.

Able to select the user from the list; when asking for `Select one or more peers to request approval from. To activate the role, at least one of your peers has to approve your request.`

User which is in the correct group gets the relevant email... but then when trying to approves get an error: '"Accessing the activation request failed: The calling user is not authorized to access this approval request"'

**Comment by jpassing** [comment]
> '"Accessing the activation request failed: The calling user is not authorized to access this approval request"'

This error doesn't seem to be related to groups. Instead, it indicates that there was a username mismatch between:

* the user that was selected as reviewer
* the user the approver was signed in as

At the bottom of the page, you can see which username you're signed in with. Is it possible that you were signed in with the wrong user when trying to approve the request?

**Comment by mattatg** [comment]
It looks like when using Asset Inventory API, nested groups doesn't work.  If you add the conditional role to the user, or to a group for which they are a direct member, it works.  If the user is gaining membership through a nested group it fails.

jit_grp_a@... < team_grp_b@... < user@...

This is because the code only retrieves the groups for which the user is a direct member: https://github.com/GoogleCloudPlatform/jit-access/blob/master/sources/src/main/java/com/google/solutions/jitaccess/core/clients/DirectoryGroupsClient.java#L90

**Comment by jpassing** [comment]
> It looks like when using Asset Inventory API, nested groups doesn't work.

Yes, that's correct and [documented here](https://googlecloudplatform.github.io/jit-access/configure-catalogs/#:~:text=The%20catalog%20ignores%20nested%20group%20memberships%20when%20evaluating%20IAM%20policies.)

If you need nested group support and have an SCC Premium subscription, you can switch to the `PolicyAnalyzer` catalog.

**Comment by chris-cjwcsl** [comment]
> > '"Accessing the activation request failed: The calling user is not authorized to access this approval request"'
> 
> This error doesn't seem to be related to groups. Instead, it indicates that there was a username mismatch between:
> 
> * the user that was selected as reviewer
> * the user the approver was signed in as
> 
> At the bottom of the page, you can see which username you're signed in with. Is it possible that you were signed in with the wrong user when trying to approve the request?

It appears the organisation changed names and used aliases (in google workspace).  So the user IAM group name is different from the email; I am happy to correct the IAM groups to contain the same name as the email.

Thanks for the quick response.

**Comment by ottlngr** [comment]
To bring this off from my side:

Group resolution works for me using v1.7.0, Cloud Run and the `AssetInventory` API.

**Comment by jpassing** [comment]
That is good to hear, thank you. I suspect that the root cause was #369 then.
