### ISSUE TITLE
Issue with listing projects

### ISSUE THREAD

**Issue by chris-johnstone** [GoogleCloudPlatform/jit-access#229]
I am currently having issues of even selecting a project when the JIT portal has been deployed on Cloud Run, the error reads `The project doesn't exist, or you don't have permission to activate any roles in this project`. I have the service account defined in the yaml file and the correct role bindings at the level in the hierachy I require, I have tried both folder and org level each time updating the app.yaml to specify the resource where the bindings are set, but still getting issues. Can anyone help?

**Comment by jpassing** [comment]
Do the Cloud Run logs contain any warnings or errors? There are some cases in which the application can't access a project because of VPC-SC policies, but then you'd see a warning or error in the logs.

If the logs are clean, it would be good to double-check that...

1. The application's service account has [both Security Admin and Cloud Asset Viewer access](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#grant-the-just-in-time-access-application-permission-to-manage-iam-bindings) to the organization, folder, or project referenced in `RESOURCE_SCOPE`. Make sure that it's indeed the `jitaccess@...` service account, and not one of the other service accounts that you've granted these roles.
2. You've [granted your test user eligible access](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#grant_eligible_access) to a project underneath `RESOURCE_SCOPE`.
3. When accessing the JIT Access UI, you're signed in with the right test user (the username is shown in the footer).

**Comment by chris-johnstone** [comment]
Thanks, went through step 2 again using a seperate user and this fixed the issue I was having .

**Comment by jpassing** [comment]
Great, happy to hear that it works now.
