### ISSUE TITLE
[Penetration Test] Implement back end controls on actions preformed by the user. Never trust user input. 

### ISSUE THREAD

**Issue by elamcheliyan** [GoogleCloudPlatform/jit-access#421]
Tamper the application by providing invalid peers in the payload using the burp proxy tool. See for example,

![image](https://github.com/GoogleCloudPlatform/jit-access/assets/65539745/4dac06ab-2f00-40c5-b4c9-e47622d2940d).

The problem was fixed in the **Sources/src/main/java/com/../../../web/rest/ApiResource.java** 
Method : public ActivationStatusResponse requestActivation( )
by imposing the below changes
This specific way of fixing it may not be correct. I have done a quick fix to close our security issues. However, if you need some improvements, please incorporate the next version. 

List<String> peerList = new ArrayList<String>(); 
 try {
        var peers = this.mpaCatalog.listReviewers(
        iapPrincipal.getId(),
        new ProjectRoleBinding(roleBinding));
        Iterator value = peers.iterator();
        while (value.hasNext())
        {
          peerList.add(value.next().toString());
      
        }
    }
    catch (Exception e) {
      this.logAdapter
        .newErrorEntry(
          LogEvents.API_LIST_PEERS,
          String.format("Listing peers failed: %s", Exceptions.getFullMessage(e)))
        .addLabels(le -> addLabels(le, e))
        .addLabels(le -> addLabels(le, roleBinding))
        .addLabels(le -> addLabels(le, projectId))
        .write();

      throw new AccessDeniedException("Listing peers failed, see logs for details");
    }
    for (int i = 0; i < request.peers.size(); i++ )
    {
      if (!(peerList.contains(request.peers.get(i))))
      {
        isvalidReviewer = false;
        break;
      }
    }

Preconditions.checkArgument(
        isvalidReviewer,
        String.format("Invalid reviewer present in the reviwers list"));

**Comment by jpassing** [comment]
That's accurate, but this behavior is actually intentional:

1. When a user requests approval for a role, the app verifies that the user is allowed to do so ([`verifyUserCanRequest`](https://github.com/GoogleCloudPlatform/jit-access/blob/df2f0180bc8d44db2f1899e992dda03132befc0f/sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/MpaProjectRoleCatalog.java#L214)). It does _not_ (as you describe) check that the approver is really allowed to approve, or even exists.
2. When the approver tries to approve, the app verifies that the user is allowed to do so ([`verifyUserCanApprove`](https://github.com/GoogleCloudPlatform/jit-access/blob/df2f0180bc8d44db2f1899e992dda03132befc0f/sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/MpaProjectRoleCatalog.java#L235C15-L235C35)). 

So the check you're missing does take place -- but only once, and only in step 2. That's because verifying if a user is allowed to request or approve a role is a _very_ expensive operation that can take multiple seconds. So it was really a performance optimization.

Given that the checks do take place, I currently don't see any path for an authorization bypass or privilege escalation. By passing an invalid/unauthorized user as approver, a user causes an email to be sent to this user and this could be seen as an information leak. But the invalid/unauthorized user can't really do anything with that email.

That said, we can add an extra check in (1) to double check that the approver is valid. I don't think it adds much value, but it also won't hurt (other than performance).

**Comment by elamcheliyan** [comment]
Thanks, since the second point is already implemented ( **When the approver tries to approve, the app verifies that the user is allowed to do so ([verifyUserCanApprove](https://github.com/GoogleCloudPlatform/jit-access/blob/df2f0180bc8d44db2f1899e992dda03132befc0f/sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/MpaProjectRoleCatalog.java#L235C15-L235C35)).**)
They created this issue with medium risk, even if this had not been implemented it could have been raised as a Higher risk :-)

**Comment by jpassing** [comment]
> They created this issue with medium risk, If this had not been implemented in the first place it could have been raised as a Higher risk

Fair enough :) I prepared a fix in #444.
