### ISSUE TITLE
What are the RBAC/IAM requirements for this service

### ISSUE THREAD

**Issue by KingBain** [GoogleCloudPlatform/jit-access#47]
I know the documentation makes mention of

 `'Super-admin access to the Cloud Identity or Google Workspace account that corresponds to the Google Cloud organization that you're using.'` 
 
 But I am curious if it can operate with less. If we dont have org level permissions can this work further down at the folder lervel to delegate down to sub folder/project levels. 

Can it ?

**Comment by adriantr** [comment]
It's a bit less and should be sufficient with `"roles/cloudasset.viewer", "roles/iam.securityAdmin"` for the project/folder/org where JIT will provide access

**Comment by jpassing** [comment]
Adding to what Adrian said, the application's service account needs:

1. `roles/cloudasset.viewer` and `roles/iam.securityAdmin` on the project/folder/org that you want the app to manage access to. JIT Access needs these roles to surface eligible role bindings and create temporary role bindings.
2. `Groups Reader` in the Workspace/Cloud Identity account.  Strictly speaking, this is optional, but if you don't grant this role, JIT Access won't be able to resolve group memberships and any eligible roles granted to groups won't show up in the tool.

   It's safe to deploy the application without  `Groups Reader` access to Workspace/Cloud Identity first and grant that role later.

The super-admin access to the Cloud Identity or Google Workspace account is only needed during deployment so that you can grant (2) to the service account. But the service account itself doesn't (and can't) be a super-admin.

**Comment by jpassing** [comment]
I hope the previous comments answered your question... if not, please just reopen the issue,
