### ISSUE TITLE
At least one peer is required: (HTTP 400: error)

### ISSUE THREAD

**Issue by rojomisin** [GoogleCloudPlatform/jit-access#51]
In testing the MPA email workflow I found that if I selected about 10 out of the 12 members of our group to request approval from, it would error out

```
At least one peer is required: (HTTP 400: error)
```

<img width="566" alt="Screenshot 2023-03-08 at 8 13 30 PM" src="https://user-images.githubusercontent.com/3313148/223915267-dd96fe5e-12c9-4888-999a-395aa4359cc4.png">

Selecting only a few members allowed the approval request to proceed

**Comment by jpassing** [comment]
The number of approvers is currently [limited to 10](https://github.com/GoogleCloudPlatform/jit-access/blob/master/sources/src/main/java/com/google/solutions/jitaccess/web/ApiResource.java#L380). That limit is arguably too low, and the error message is misleading too.

Thanks for flagging this.

**Comment by rojomisin** [comment]
We are using a group w/ 12 members, but should it allow the group itself to be displayed as a checkbox (as a single approver), perhaps in an expandable list?  If we had a group: principal which is used with 4 subgroups, that is our use-case, to choose which team to send to for approval instead of individuals.

Like:
- [ ] engineering
  - [ ] team a
    - [ ] bob
    - [ ] alice
  - [ ] team b
...

**Comment by jpassing** [comment]
I created a fix that introduces a new environment variable `ACTIVATION_REQUEST_MAX_REVIEWERS`. Using this variable, you can customize the maximum number of peers that users can select as reviewers. The default is still `10`.

> We are using a group w/ 12 members, but should it allow the group itself to be displayed as a checkbox (as a single approver), perhaps in an expandable list?

The application (or the Policy Analyzer API, to be precise) expands groups, so you should only see users in that list.

Changing the behavior to show groups might be tricky:

* We could disable group expansion so that groups are shown just as they're listed in an IAM policy. But then users have no way of seeing whether the group actually contains any members, or whether it's a group with hundreds of members. 

  The fact that a group has access to a resource also doesn't necessarily mean that all members have access too, as some members might be subject to a deny policy.
* Showing both, the group and its members might be an option. But it might be quite inefficient as the Policy Analyzer API can only return one of the two, so the app would need to make 2 calls.

**Comment by rojomisin** [comment]
Great, yes the expandable groups is not a must-have, as long as we can control the max reviewers that's great, thank you for the fix.

I received some feedback from our teams on the approval email, will submit those as new feature request issues.

**Comment by jpassing** [comment]
Ok, thanks. I'll close this issue then and will await your additional feature request regarding the approval emails.
