### ISSUE TITLE
ability to "select all" before role activation

### ISSUE THREAD

**Issue by masonsteinberg** [GoogleCloudPlatform/jit-access#59]
Could we have a simple "Select all" checkbox on the web UI when there are multiple roles to be activated? Imagine a scenario with 5-8 roles available for activation, could we have a "select all" instead of manually checking all checkboxes one-by-one?

**Comment by lnrdll** [comment]
+1

**Comment by jpassing** [comment]
There are two scenarios to consider here:

1. The list only shows JIT-eligible roles (i.e., roles that require activation, but no approval)
2. The list shows a mixture of JIT-eligible roles and MPA-eligible roles (i.e., roles that require multi-party approval)

For JIT-eligible roles, the app already lets you select and activate multiple roles at once. Adding a "select all" button would be an easy thing to do.

But for MPA-eligible roles, the app only lets you activate one role at a time because the list of eligible reviewers might be different for each role. So a "select all" button wouldn't work if there's one or more MPA-eligible roles in the list.

I suppose the easiest way to deal with that would be to show the "select all" button in case of (1), and hide it in case of (2). Wdyt?

**Comment by jpassing** [comment]
This feature is now available in [release 1.4](https://github.com/GoogleCloudPlatform/jit-access/releases/tag/1.4.0).
