### ISSUE TITLE
build of dockerfile as part of build pipeline

### ISSUE THREAD

**Issue by adriantr** [GoogleCloudPlatform/jit-access#63]
We're currently lacking registry & building itself of dockerfile as part of CI pipeline.

I can implement that functionality so we can have official JIT image repo, but I'm not sure where's the right place to store the container images? Do you know @jpassing?

**Comment by jpassing** [comment]
I agree that a pre-built image would make the deployment a bit easier. But it's difficult to keep container images up-to-date and fully patched at all times, which is why we generally don't provide pre-built images for open-source projects. So the lack of pre-built images is currently deliberate and I'm afraid not something we can change.

**Comment by adriantr** [comment]
Fair enough - closing !
