### ISSUE TITLE
Add support for resource-level JIT access

### ISSUE THREAD

**Issue by l-gray** [GoogleCloudPlatform/jit-access#66]
This is half question, half suggestion, but it doesn't look like this supports IAM bindings below project in the hierarchy (right?).  In our case, we'd like to add JIT access to individual GCS buckets, but after entering the appropriate project in step 1 of the request workflow, the roles that are returned don't include the bucket-level bindings.  Would it be possible to add support for individual resources (if it doesn't already exist)?

**Comment by jpassing** [comment]
> It it doesn't look like this supports IAM bindings below project in the hierarchy

Yes, that's correct. Unfortunately, adding support for resource-level bindings is challenging, primarily for two reasons:

1. To list eligible role bindings, JIT Access would have to analyze the IAM policies of all resources within a project. The Asset API (which JIT Access uses) does support this, but it quickly becomes inefficient as the number of resources grow and for large projects, it's not possible to perform this kind of analysis "in real time" anymore, leading to truncated results.
2. There's no single API for modifying resource-level IAM policies. For ex, to modify the policy of a VM instance, JIT Access would have to use the Compute Engine API, for a Cloud Storae bucket, the Storage API, etc. 

What might be possible is adding support for IAM conditions like `has({}.jitAccessConstraint) && resource.type == "storage.googleapis.com/Object" && resource.name.startsWith("projects/_/buckets/exampleco-site-assets/")`. This wouldn't work for [all resource types](https://cloud.google.com/iam/docs/conditions-resource-attributes#resource-type) however.

**Comment by l-gray** [comment]
Fair enough, thanks for the suggested workaround @jpassing!

**Comment by l-gray** [comment]
@jpassing , I was just testing this out a bit myself after some of our users experienced issues.  It doesn't look like the tool presents eligible roles with both the `has({}.jitAccessConstraint)` condition and additional resource conditions (e.g.,  `resource.name` like you gave in your example).  It also doesn't seem to present roles with a time condition.

**Comment by jpassing** [comment]
I'm sorry, I guess my previous comment was a bit misleading. Currently, JIT Access doesn't let you "combine" IAM conditions. So a condition like `has({}.jitAccessConstraint) && resource.type == "storage.googleapis.com/Object" && resource.name.startsWith("projects/_/buckets/exampleco-site-assets/")` won't work, just like you said.

What I meant to say in my previous comment that it would be possible to add support for those kinds of conditions, but that would be a new feature.

**Comment by l-gray** [comment]
Thanks for clarifying, @jpassing.  We'd certainly appreciate that feature.

**Comment by rialg** [comment]
@jpassing I was about to create a new issue, when I stumbled with [your previous answer](https://github.com/GoogleCloudPlatform/jit-access/issues/66#issuecomment-1522613942). 

Besides changing the constraints in [JitConstraints.java](https://github.com/GoogleCloudPlatform/jit-access/blob/master/sources/src/main/java/com/google/solutions/jitaccess/core/services/JitConstraints.java#L33), what other source file would you suggest to update? This feature is critical for restricting access to specific secrets in GSM based on resources tags and names, so I could put together a PR for it :smile:

**Comment by jpassing** [comment]
Yes, we'd need to relax the RegEx in JitConstraints. But that's not quite sufficient yet:

* If there is an additional clause in the IAM condition of an eligible role binding (for ex, `resource.name.startsWith("projects/_/buckets/exampleco-site-assets/"`) and a user activates that role binding, then we need to "copy" this clause into the temporary role binding. 
* Currently, JIT Access considers the tuple `(role, resource, status)` (where status is JIT or MPA) to be unique (see `ProjectRole`). It's possible that a user is granted the same role multiple times (for ex, once on the project and then again on the parent folder), but in that case the two role bindings are equivalent, and there's no need for JIT Access to distinguish between those 2 bindings.

  This changes once we allow the IAM condition to contain additional clauses: Now we can grant a user the same role multiple times, but with sightly different clauses. For ex, we could create two role bindings for  `roles/storage.objectViewer`, each with a different condition:
  1.    `has({}.jitAccessConstraint) && resource.name.startsWith("projects/_/buckets/FOO/")`
  2.    `has({}.jitAccessConstraint) && resource.name.startsWith("projects/_/buckets/BAR/")`

  These two role bindings aren't equivalent anymore and we'd need to make sure that:
  
  * The two roles are both surfaced in the UI, somehow indicating that they have a different condition and thus apply to different resources.
  * Depending on which one the user decides to activate, we need to use the right clause and add it to the temporary binding.
  * In case of multi-party approval, we also need to surface the condition to the reviewer, because it might impact their decision.

So the required changes are quite significant, unfortunately.

There is one other thing I'm a bit worried about: Because we're currently not allowing any complex IAM conditions (i.e., conditions that involve multiple clauses), it's sufficient for  `JitConstraints` to parse the condition with a RegEx. But evaluating the IAM condition becomes more tricky once we allow additional clauses: For example, someone might use a condition like `(has({}.jitAccessConstraint) ||  has({}.multiPartyApprovalConstraint)` or `has({}.multiPartyApprovalConstraint) || resource.name=='...'`. It's not clear what the semantics of such conditions would be and, more critically, it'll be difficult to evaluate such complex conditions with a RegEx-based approach.

**Comment by rialg** [comment]
@jpassing since #87 has been overlooked for the past releases, I will proceed to close it. Nevertheless, I do still believe that there is a need for more fine-grained control over the roles which the users can request a temporary binding to, thus, this issue will remain open.

**Comment by jpassing** [comment]
This feature is now available as [resource conditions](https://googlecloudplatform.github.io/jit-access/resource-conditions/) in [release 1.8](https://github.com/GoogleCloudPlatform/jit-access/releases/tag/1.8.0).

Thank you @rialg for your contributions, and my apologies that it took so long.
