### ISSUE TITLE
The project doesn't exist, or you don't have permission to activate any roles in this project

### ISSUE THREAD

**Issue by losisin** [GoogleCloudPlatform/jit-access#81]
Hello,

We are looking into using this tool for our org because it definitely ticks all the boxes. Our setup is on Cloud Run with ingress `internal-and-cloud-load-balancing`.  Members of our org can login properly so I guess brand and client are set correctly. However, when selecting project it's not possible to continue to next step with the error message `The project doesn't exist, or you don't have permission to activate any roles in this project`. I doubt that project is an issue because they are listed properly with auto-complete.

`jitaccess` service account has Security Admin, Cloud Asset Viewer and Cloud Debugger Agent roles. I wasn't able to find anything in Cloud Run logs. Request to `api/projects/PROJECT_ID/roles` returns empty response `{"warnings":[],"roles":[]}`. 

Things I've tried so far:
- deploy from `master` and `latest` branch
- cloud run with `projects/XXXXXX` and `organizations/XXXXXXX`
- same project as cloud run deployment and different project
- conditional roles for both `user` and `group`

Any guidance would be greatly appreciated!

**Comment by jpassing** [comment]
The project autocompleter lists projects for which you have the `resourcemanager.projects.get` permission (which is the lowest level of access you can have to a project). It considers both permanent role bindings (i.e., bindings with no IAM conditions) and eligible role bindings (i.e., bindings with IAM condition `has({}.jitAccessConstraint)` or `has({}.jitAccessConstraint)`).

If a project shows up in the autocompleter, but clicking Continue gives you a _The project doesn't exist, or you don't have permission to activate any roles in this project_ error, then the issue is probably that:

* you have a _permanent_ role binding for the project that grants you the `resourcemanager.projects.get` permission, but
* you don't have any _eligible_ role bindings for the project, or at least JIT Access couldn't find any

If you haven't already, it might be worth double-checking the following:

* do your eligible role bindings have the right IAM condition (`has({}.jitAccessConstraint)` or `has({}.jitAccessConstraint)`)?
* did you grant the application's service account _Groups Reader_ access in Cloud Identity/Workspace? Otherwise JIT Access won't find any eligible role bindings granted to groups.
* are your elible role bindings in scope? For example, if you deployed JIT Access with `RESOURCE_SCOPE=folders/123`, then JIT Access only considers IAM bindings underneath this folder, but ignores any IAM bindings granted on parent folders or the organization. Similarly, if you deployed with `RESOURCE_SCOPE=projects/123`, then JIT Access ignores any folder- or org-level bindings.
* did you grant the service account the _Security Admin, Cloud Asset Viewer_ roles to the project/folder/org pointed to by `RESOURCE_SCOPE`?
