### ISSUE TITLE
"You don't have permission to get the role at organizations/ORG_ID/roles" 

### ISSUE THREAD

**Issue by damiansztankowski** [GoogleCloudPlatform/jit-access#91]
Hi,

 For access purposes I've created custom role at organization level and assigned this role to principal at folder level with CEL condition. Unfortunately I'm getting error "You don't have permission to get the role at organizations/ORG_ID/roles" even if Organization Policy Viewer is assigned at folder or organization level. I've configured predefined roles ( screenshot ) and this role is able to activated.
 So my question is, whether JIT is able to use custom roles at folder level, or I must grant predefined roles. It's important as per needs, I must use more that 10 RO predefined roles. 
 
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/71320767/e29148ad-e55a-4226-88c5-25b51ea82cd2)

**Comment by damiansztankowski** [comment]
I've configured the same custom role, but without CEL condition and checked if I'm able to see resources and use permissions from that role, and it works.

**Comment by jpassing** [comment]
I had a closer look at this:

* When you deploy JIT Access and set [`RESOURCE_SCOPE`](https://github.com/GoogleCloudPlatform/jit-access/wiki/Configuration#:~:text=Basic%20configuration-,RESOURCE_SCOPE,-The%20organization%2C%20folder) to your organization node, then all custom roles should work fine.
* When you set `RESOURCE_SCOPE` to a folder or project, then project-level custom roles will work. However, custom roles defined at the organization level won't work, and will instead cause a warning to be displayed ("You don't have permission..."). That's probably what happened in your case.

This behavior comes from the Policy Analyzer API that JIT Access uses to determine eligible roles, so there isn't much we can do in the app to change that. But it's something worth documenting because this behavior isn't super obvious.

**Comment by damiansztankowski** [comment]
I see. I've handled it anyway, but yes, information about that would be time saving.

**Comment by jpassing** [comment]
I added [a paragraph to the documentation](https://github.com/GoogleCloudPlatform/jit-access/wiki/Configuration#:~:text=The%20types%20of,the%20organization%20level.) and created  #92 to ensure that the toast doesn't show the same warning message multiple times.
